AboutPage: Update with current text
sailfishos-chum/sailfishos-chum-gui pull request #102
Opened 2022-02-07 22:56 UTC by Olf0

… from https://github.com/sailfishos-chum/main/blob/main/README.md
Plus use consistent wording and sort issue tracker before source code link.

2022-02-07 23:59 UTC, Olf0 commented
I hope to have got the syntax right in the `%//` text sections, especially https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/files#diff-91cbf11fb1958c047c46ddb91ba505b284cbd428455c3ba076cf4ab1f4952918R65-R99
Please check.

2022-02-09 21:03 UTC, rinigus commented
Thanks for looking through the messages. That would need some testing, maybe has to wait few days more.

2022-02-10 18:53 UTC, rinigus requested changes
Thank you very much for this improvement. I have tested on XZ2c which is on a smaller side of the screen allowing me to test GUI in what is probably more unforgiving case in terms of line breaks.

Here are the issues I found, please revise

2022-02-10 18:53 UTC, rinigus commented on qml/pages/AboutPage.qml
>              }
```suggestion
                wrapMode: Text.WordWrap
            }
```

Please add to fit the screen

2022-02-10 18:53 UTC, rinigus commented on qml/pages/MainPage.qml
> +                title: "SailfishOS:Chum GUI"
I prefer it without GUI and having a shorter form: SailfishOS:Chum. But if you feel strongly about it, can be with GUI as well

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                                    //% "Subscribed to the SailfishOS:Chum testing repository with a manually set Sailfish&nbsp;OS version (%1)."
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                                    //% "Subscribed to the regular SailfishOS:Chum repository with a manually set Sailfish&nbsp;OS version (%1)."
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                                //% "Subscribed to the SailfishOS:Chum testing repository with an automatically determined Sailfish&nbsp;OS version."
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                                //% "Subscribed to the regular SailfishOS:Chum repository with an automatically determined Sailfish&nbsp;OS version."
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                //% "a specific Sailfish&nbsp;OS release, specify this Sailfish&nbsp;OS release here (for example, 4.3.0.12). "
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                //% "installed Sailfish&nbsp;OS release version. To subscribe to a SailfishOS:Chum repository for "
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                //% "Sailfish&nbsp;OS version, as for Cbeta users."
&nbsp; doesn't work here, please revert

2022-02-10 18:53 UTC, rinigus commented on qml/pages/SettingsPage.qml
> +                //% "Specify a Sailfish&nbsp;OS version"
&nbsp; doesn't work here, please revert

2022-02-10 19:29 UTC, Olf0 commented on qml/pages/AboutPage.qml
> +                //% "About the SailfishOS:Chum GUI"
Oh, this is an error: I already anticipated that "SailfishOS:Chum GUI application" (here additionally prefixed with "About the ") will likely be too long and thus deleted the "application".  I missed to delete the then superfluous "the ".  Done now per https://github.com/Olf0/sailfishos-chum-gui/commit/df487a3e7766b3db18fb6a2f7c899d6df6eaadf9

If it is still too long, then your suggestion is likely the proper way to go (and I have no idea about the proper syntax for that).

2022-02-10 19:49 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                //% "Sailfish&nbsp;OS version, as for Cbeta users."
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:49 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                //% "installed Sailfish&nbsp;OS release version. To subscribe to a SailfishOS:Chum repository for "
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:50 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                                //% "Subscribed to the regular SailfishOS:Chum repository with an automatically determined Sailfish&nbsp;OS version."
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:50 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                                    //% "Subscribed to the regular SailfishOS:Chum repository with a manually set Sailfish&nbsp;OS version (%1)."
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:50 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                                //% "Subscribed to the SailfishOS:Chum testing repository with an automatically determined Sailfish&nbsp;OS version."
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:51 UTC, Olf0 commented on qml/pages/SettingsPage.qml
> +                                    //% "Subscribed to the SailfishOS:Chum testing repository with a manually set Sailfish&nbsp;OS version (%1)."
Reverted by https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/dfb6335f4c5708b3b86957ce15c5de335344d76e

2022-02-10 19:55 UTC, Olf0 commented
I also reverted the "&nbsp;" in the AboutPage, even though you did not mention them: Was that premature?
I.e., did they work there, although they did not work in the SettingsPage? 

If so, please revert https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/102/commits/5308a2eede3c572440a5a61a640c1936e9d2899a before merging.

2022-02-10 20:41 UTC, rinigus commented
> I also reverted the "&nbsp;" in the AboutPage, even though you did not mention them as non-functional: Was that premature?
> I.e., did they work there, although they did not work in the SettingsPage?

It does work in About as it is parsed with HTML subset (`textFormat: Text.StyledText`). It is easier for me to merge first and then revert it. 

As for About page title, I think it will fit in without "the". If not, will make subheader later.

Thank you, merging.

2022-02-10 20:41 UTC, merged

2022-02-10 21:54 UTC, Olf0 commented
Thank you, this is looking good.

If you want me to take a final look at it on my XperiaX@SFOS3.2.1, notify me when you have uploaded it to the SailfishOS:Chum testing repository.

2022-02-11 07:35 UTC, rinigus commented
I have just bumped it in :testing repo, should be ready in 10min or so.

2022-02-15 17:02 UTC, rinigus commented
About page is fixed in ca447462e76e461ec0cc3f484788dee8f018e6aa - pushed it directly into the main branch. Corresponding build has been started in :testing, would expect it to be ready soon